import os
import sys

import pandas as pd
import streamlit as st
from dotenv import load_dotenv

load_dotenv()
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

from src.database.connection import init_db, get_connection
from src.database.queries import (
    get_latest_forecast_run,
    get_all_transactions,
    get_recurring_payments,
    get_anomalies,
    save_forecast_run,
)
from src.explanation.deepseek import generate_forecast_narrative

init_db()

st.title("Narrative")
st.markdown("Plain-language forecast commentary generated by DeepSeek.")
st.divider()

run = get_latest_forecast_run()
if not run:
    st.info("No forecast found. Go to **Home** and run the pipeline first.")
    st.stop()

# ── Display existing narrative ────────────────────────────────────────────────
narrative = run.get("narrative", "")

if narrative:
    st.markdown("### Latest Commentary")
    st.markdown(
        f'<div style="background:#f8f9fa;border-left:4px solid #4682b4;'
        f'padding:1rem 1.2rem;border-radius:4px;font-size:1rem;line-height:1.7;">'
        f"{narrative}</div>",
        unsafe_allow_html=True,
    )
    st.caption(f"Generated for forecast run #{run['id']} on {run.get('run_date', 'N/A')}")
else:
    st.warning("No narrative for this forecast run. Click below to generate one.")

st.divider()

# ── Forecast context ──────────────────────────────────────────────────────────
with st.expander("Forecast inputs used"):
    c1, c2 = st.columns(2)
    c1.markdown(f"**Opening balance:** RM {run.get('opening_balance', 0):,.2f}")
    c1.markdown(f"**30-day net flow:** RM {run.get('forecast_30', 0):,.2f}")
    c1.markdown(f"**60-day net flow:** RM {run.get('forecast_60', 0):,.2f}")
    c2.markdown(f"**90-day net flow:** RM {run.get('forecast_90', 0):,.2f}")
    c2.markdown(f"**Closing balance:** RM {run.get('closing_balance', 0):,.2f}")
    c2.markdown(f"**Shortfall risk:** {run.get('shortfall_risk', 'NONE')}")

st.divider()

# ── Regenerate ────────────────────────────────────────────────────────────────
st.subheader("Regenerate Commentary")
st.caption("This calls the DeepSeek API and will count against your usage quota.")

if st.button("Generate new narrative", type="primary"):
    tx_df = get_all_transactions()
    if tx_df.empty:
        st.error("No transactions in the database.")
        st.stop()

    tx_df["date"] = pd.to_datetime(tx_df["date"])
    cutoff = tx_df["date"].max() - pd.Timedelta(days=90)
    recent = tx_df[tx_df["date"] >= cutoff]
    months = max(1, (tx_df["date"].max() - cutoff).days / 30)

    avg_inflow  = recent[recent["type"] == "inflow"]["amount"].sum() / months
    avg_outflow = recent[recent["type"] == "outflow"]["amount"].sum() / months
    avg_net     = avg_inflow - avg_outflow

    rec_df = get_recurring_payments()
    ano_df = get_anomalies()

    from src.analysis.recurring import RecurringPayment
    from src.analysis.anomaly import Anomaly
    from datetime import date as dt_date

    rec_list = [
        RecurringPayment(
            description=r["description"], category=r["category"],
            average_amount=r["average_amount"], frequency=r["frequency"],
            last_occurrence=dt_date.fromisoformat(r["last_occurrence"]),
            next_expected=dt_date.fromisoformat(r["next_expected"]),
            confidence=r["confidence"], is_inflow=bool(r["is_inflow"]),
        )
        for _, r in rec_df.iterrows()
    ]
    ano_list = [
        Anomaly(
            transaction_id=r.get("transaction_id"),
            anomaly_type=r["anomaly_type"], severity=r["severity"],
            description=r["description"],
        )
        for _, r in ano_df.iterrows()
    ]

    with st.spinner("Calling DeepSeek..."):
        new_narrative = generate_forecast_narrative(
            avg_inflow=avg_inflow, avg_outflow=avg_outflow, avg_net=avg_net,
            current_balance=run.get("opening_balance", 0),
            forecast_30=run.get("forecast_30", 0),
            forecast_60=run.get("forecast_60", 0),
            forecast_90=run.get("forecast_90", 0),
            closing_balance=run.get("closing_balance", 0),
            shortfall_risk=run.get("shortfall_risk", "NONE"),
            recurring_list=rec_list,
            anomaly_list=ano_list,
        )

    if new_narrative:
        conn = get_connection()
        conn.execute(
            "UPDATE forecast_runs SET narrative=? WHERE id=?",
            (new_narrative, run["id"]),
        )
        conn.commit()
        conn.close()
        st.success("Narrative updated.")
        st.markdown(
            f'<div style="background:#f8f9fa;border-left:4px solid #4682b4;'
            f'padding:1rem 1.2rem;border-radius:4px;font-size:1rem;line-height:1.7;">'
            f"{new_narrative}</div>",
            unsafe_allow_html=True,
        )
    else:
        st.error("DeepSeek returned an empty response. Check your API key.")
